### ISSUE TITLE
Error when using example workflow

### ISSUE THREAD

**Issue by popovidis** [kijai/ComfyUI-LivePortraitKJ#12]
```
2024-07-05 12:56:03.568554311 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

[12:56:03] LandmarkRunner warmup time: 0.027s              landmark_runner.py:89
2024-07-05 12:56:03.786485287 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /workspace/ComfyUI/models/insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
2024-07-05 12:56:03.914326696 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /workspace/ComfyUI/models/insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
2024-07-05 12:56:03.952310361 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /workspace/ComfyUI/models/insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
2024-07-05 12:56:03.995014228 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /workspace/ComfyUI/models/insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
2024-07-05 12:56:04.089183904 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /workspace/ComfyUI/models/insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (512, 512)
[12:56:04] FaceAnalysisDIY warmup time: 0.023s           face_analysis_diy.py:79
[ WARN:0@271.920] global loadsave.cpp:241 findDecoder imread_('/workspace/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ/liveportrait/./utils/resources/mask_template.png'): can't open/read file: check file path/integrity
!!! Exception during processing!!! OpenCV(4.10.0) /io/opencv/modules/imgproc/src/imgwarp.cpp:2825: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'warpAffine'

Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/workspace/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ/nodes.py", line 260, in process
    cropped_frames, full_frame = pipeline.execute(img, driving_images_np)
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ/liveportrait/live_portrait_pipeline.py", line 98, in execute
    mask_ori = _transform_img(inference_cfg.mask_crop, crop_info['M_c2o'], dsize=(img_rgb.shape[1], img_rgb.shape[0]))
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ/liveportrait/utils/crop.py", line 30, in _transform_img
    return cv2.warpAffine(img, M[:2, :], dsize=_dsize, flags=flags)
cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/imgwarp.cpp:2825: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'warpAffine'
```

**Comment by xiety** [comment]
Maybe, this is because your `mask_template.png` file contains text not an image.

Get correct file from this repository:

https://github.com/KwaiVGI/LivePortrait/blob/main/src/utils/resources/mask_template.png

**Comment by popovidis** [comment]
> Maybe, this is because your `mask_template.png` file contains text not an image.
> 
> Get correct file from this repository:
> 
> https://github.com/KwaiVGI/LivePortrait/blob/main/src/utils/resources/mask_template.png

the error has multiple files missing, also what do I do with this mask_template?

**Comment by xiety** [comment]
Put correct image file `mask_template.png` over incorrect file in your `custom_nodes/ComfyUI-LivePortraitKJ/liveportrait/utils/resources`

And make sure you have extracted insightface models in `ComfyUI/models/insightface/buffalo_l`

https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip

**Comment by popovidis** [comment]
> Put correct image file `mask_template.png` over incorrect file in your `custom_nodes/ComfyUI-LivePortraitKJ/liveportrait/utils/resources`
> 
> And make sure you have extracted insightface models in `ComfyUI/models/insightface/buffalo_l`
> 
> https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip

that worked thank you
