### ISSUE TITLE
Once expression_friendly is set to true, the system reports an error that expression_friendly works only with single source image

### ISSUE THREAD

**Issue by realyn** [kijai/ComfyUI-LivePortraitKJ#125]
!!! Exception during processing!!! expression_friendly works only with single source image
Traceback (most recent call last):
  File "E:\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\nodes.py", line 319, in process
    raise ValueError("expression_friendly works only with single source image")
ValueError: expression_friendly works only with single source image

use live_portrait_video sample workflow

**Comment by kijai** [comment]
That's right, expression friendly only works with single image sources, not video sources.
