### ISSUE TITLE
ValueError: could not broadcast input array from shape (9,9) into shape (9,1)

### ISSUE THREAD

**Issue by reefor** [kijai/ComfyUI-LivePortraitKJ#147]
Hi. I went back to the standard pic to vid version after having some issues with the new pic to vid version. I think it's a great idea, it just still early in the development I guess. Plus I really like the Blackface Back Camera cropper. It seems to give better results with lip movement.

Anyway, I'm still having problems with the output video having a shaky head and I just saw for the first time the setting in the LivePortrait Process node called "relative motion node". I want to try the "Source_Video_Smoothed" option to see if it helps with it, but when I try I get an error message that's way beyond me. Can someone tell me what this means and if there's a way to fix it?

I'm running it in Comyui Portable on a Windows machine and I think I have all the right Python & Cuda & C++ installed. Everything else is working.

!!! Exception during processing !!! could not broadcast input array from shape (9,9) into shape (9,1)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\nodes.py", line 349, in process
    out = pipeline.execute(
          ^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\liveportrait\live_portrait_pipeline.py", line 107, in execute
    driving_rot_list_smooth = smooth(x_d_r_lst, source_rot_list[0].shape, device, observation_variance=driving_smooth_observation_variance)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\liveportrait\utils\filter.py", line 22, in smooth
    smoothed_state_means, _ = kf.smooth(x_d_stacked)
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pykalman\standard.py", line 1323, in smooth
    _filter(
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pykalman\standard.py", line 386, in _filter
    (kalman_gains[t], filtered_state_means[t],
     ~~~~~~~~~~~~^^^
ValueError: could not broadcast input array from shape (9,9) into shape (9,1)

**Comment by MaratG2** [comment]
+1

**Comment by fafayqa** [comment]
+1

**Comment by Maelstrom2014** [comment]
+1

**Comment by dAItime001** [comment]
+1

**Comment by vararth** [comment]
+1
