### ISSUE TITLE
cv::warpAffine'

### ISSUE THREAD

**Issue by StartHua** [kijai/ComfyUI-LivePortraitKJ#2]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\Comfyui\ComfyUI_windows_portable\ComfyUI\models\insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (512, 512)
[10:17:08] FaceAnalysisDIY warmup time: 0.085s                                                   face_analysis_diy.py:79!!! Exception during processing!!! OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2825: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

Traceback (most recent call last):
  File "E:\Comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
              
  File "E:\Comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))

  File "E:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortrait\nodes.py", line 256, in process
    cropped_frames, full_frame = pipeline.execute(img, driving_images_np)
                               
  File "E:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortrait\liveportrait\live_portrait_pipeline.py", line 98, in execute
    mask_ori = _transform_img(inference_cfg.mask_crop, crop_info['M_c2o'], dsize=(img_rgb.shape[1], img_rgb.shape[0]))

  File "E:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortrait\liveportrait\utils\crop.py", line 30, in _transform_img
    return cv2.warpAffine(img, M[:2, :], dsize=_dsize, flags=flags)

cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2825: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

**Comment by xiety** [comment]
Maybe, this is because your `mask_template.png` file contains text not an image.

Get correct file from this repository:

https://github.com/KwaiVGI/LivePortrait/blob/main/src/utils/resources/mask_template.png

**Comment by kijai** [comment]
> Maybe, this is because your `mask_template.png` file contains text not an image.
> 
> Get correct file from this repository:
> 
> https://github.com/KwaiVGI/LivePortrait/blob/main/src/utils/resources/mask_template.png

The file on this repo is actually fine, but to to elaborate what happened: The original repo had marked all the media files to use LFS, which I honestly have never used so I was unaware, people cloning this repo filled my quota hard:

![image](https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/40791699/ba27e5af-462e-4617-a9a5-0ebc316a9c03)

Thus after it was full it failed to download the media files, which included the mask_template.png, causing cv2 to error out when receiving empty image.
