### ISSUE TITLE
albumentations  module missing and i can't get it installed properly 

### ISSUE THREAD

**Issue by zahdab** [kijai/ComfyUI-LivePortraitKJ#20]
I manged to get insightface installed by installing reactor thought i get the below error on launching comfyui 

Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1907, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 27, in <module>
    from scripts.reactor_faceswap import (
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 14, in <module>
    from scripts.reactor_swapper import (
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 9, in <module>
    import insightface
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
ModuleNotFoundError: No module named 'albumentations'

Cannot import D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'albumentations'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.1 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.1 seconds (IMPORT FAILED): D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortrait
   0.2 seconds (IMPORT FAILED): D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.3 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   5.7 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff

If i do a Python - pip install of albumentations  i get a "already satisfied" response 
IF i install via the comfy manager pip installer, i can launch without issues ( the worflow still doesn't transfer the animation though ) however, upon restarting comfyui i get the same error again

**Comment by zahdab** [comment]
Fixed it by Uninstalling and reinstalling the module via pip
