### ISSUE TITLE
LivePortraitCropper.process() got an unexpected keyword argument 'pipeline'

### ISSUE THREAD

**Issue by UsernamesAreSilly4** [kijai/ComfyUI-LivePortraitKJ#86]
Using the vid2vid example workflow with the latest update. A simple "queue" operation with a sample video gives this error:

```
!!! Exception during processing!!! LivePortraitCropper.process() got an unexpected keyword argument 'pipeline'
Traceback (most recent call last):
  File "c:\Lacko\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Lacko\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Lacko\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LivePortraitCropper.process() got an unexpected keyword argument 'pipeline'
```

Edit: vanilla installation, no other nodes are installed, same issue. Both MediaPipe and Insightface nodes throw the same error.

**Comment by kijai** [comment]
Something either isn't updated or you haven't restarted/refreshed after update? It's saying the Cropper node doesn't have pipeline input, which is a new addition in the update.

**Comment by UsernamesAreSilly4** [comment]
Thanks Kijai. I had to remove and re-install the "KJNodes for ComfyUI" package separately. Now it works.

Thanks for your great work and quick responses.
