### ISSUE TITLE
Error occurred when executing LivePortraitProcess:  LivePortraitProcess.process() got an unexpected keyword argument 'crop_info'  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### ISSUE THREAD

**Issue by HASAN3DG** [kijai/ComfyUI-LivePortraitKJ#87]
Hi
Error occurred when executing LivePortraitProcess:

LivePortraitProcess.process() got an unexpected keyword argument 'crop_info'

File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
![Screenshot 2024-07-25 002416](https://github.com/user-attachments/assets/77e79845-945f-4b24-bc9d-1a5f9cec9853)

**Comment by KleberReisser37** [comment]
There is a new workflow example for the updated version.
Then it works fine :-)

**Comment by Elenor274** [comment]
same problem ! 
![Untitled](https://github.com/user-attachments/assets/834fa1b0-e00f-4385-9e56-d28421807de5)

**Comment by kijai** [comment]
> same problem ! ![Untitled](https://private-user-images.githubusercontent.com/157117628/352526057-834fa1b0-e00f-4385-9e56-d28421807de5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTc2NzAsIm5iZiI6MTcyMTk5NzM3MCwicGF0aCI6Ii8xNTcxMTc2MjgvMzUyNTI2MDU3LTgzNGZhMWIwLWUwMGYtNDM4NS05ZTU2LWQyODQyMTgwN2RlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxMjM2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmFmNmEwM2Q5YmQ4YmZlNDExNWE4NTNkN2EyNGM0MDFhNWUzNmRkOTFhN2JjODFhYTg0ZWFhZGU2NzkyMGNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VS5OS1opu5BkJxjjuLxIlDhG_4hGfofpfXlnivT53z8)

Remake the node or use the new workflows, old workflows won't work as they are as the nodes have changed too much.

**Comment by bozkut** [comment]
issue is still continued any resolution?

!!! Exception during processing!!! LivePortraitProcess.process() missing 1 required positional argument: 'crop_info'
Traceback (most recent call last):
  File "C:\Users\Zeyzkut\Documents\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zeynut\Documents\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zeykut\Documents\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LivePortraitProcess.process() missing 1 required positional argument: 'crop_info'

Prompt executed in 19.06 seconds
