### ISSUE TITLE
LivePortrait处理 这个节点不能使用了？

### ISSUE THREAD

**Issue by logo66612** [kijai/ComfyUI-LivePortraitKJ#91]
Detecting, cropping, and processing..: 100%|█████████████████████████████████████████| 128/128 [00:10<00:00, 12.72it/s]
!!! Exception during processing!!! LivePortraitProcess.process() got an unexpected keyword argument 'crop_info'
Traceback (most recent call last):
  File "D:\AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LivePortraitProcess.process() got an unexpected keyword argument 'crop_info'

Prompt executed in 27.36 seconds

**Comment by kijai** [comment]
Either the workflow you're using is old or the nodes aren't up to date. Old workflows before the big update won't work as they are, the nodes need to be refreshed. I recommend making sure you're on latest version and trying one of the example workflows included first.

**Comment by logo66612** [comment]
我是刚下载的工作流，版本也刚刚更新，还是不行，提示错误：TypeError: LivePortraitProcess.process() got an unexpected keyword argument 'crop_info'

**Comment by kijai** [comment]
> I just downloaded the workflow and updated the version, but it still doesn't work. I get an error message: TypeError: LivePortraitProcess.process() got an unexpected keyword argument 'crop_info'

Then it is not updated. Also remember to refresh your browser window and restart Comfy after updating.

**Comment by crazier9527** [comment]
> 我是刚下载的工作流，版本也刚刚更新，还是不行，提示错误：TypeError: LivePortraitProcess.process() got an unexpected keyword argument 'crop_info'
You just need to roll back to the historical version. Look at the time when your workflow or video tutorial was made and roll back to the plug-in version of that time.
