### ISSUE TITLE
corp info error

### ISSUE THREAD

**Issue by raochinmay6** [kijai/ComfyUI-LivePortraitKJ#93]
see this

`Loading 1 new model
LivePortrait using fp16
Load appearance_feature_extractor done.
Load motion_extractor done.
Load warping_module done.
Load spade_generator done.
Load stitching_retargeting_module done.
!!! Exception during processing!!! LivePortraitProcess.process() missing 1 required positional argument: 'crop_info'
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LivePortraitProcess.process() missing 1 required positional argument: 'crop_info'

Prompt executed in 23.44 seconds`

**Comment by logo66612** [comment]
我也报这个错误，刚刚更新的版本和刚下载的工作流，跑到LivePortrai采样节点就报错

**Comment by raochinmay6** [comment]
me too

**Comment by raochinmay6** [comment]
please give us a solution
i think new version give us some error

**Comment by kijai** [comment]
Yeah it won't work with old workflows, the old nodes need to be refreshed/remade or just use one of the new examples.

**Comment by raochinmay6** [comment]
i face error here see the red line in my workflow 
![Screenshot (35)](https://github.com/user-attachments/assets/4c93458f-311b-44d8-8f21-1eac7d17bd30)


and also I share my workflow and please can u look into json file
[LivePortrait + AnimateDiff backgrounds.json](https://github.com/user-attachments/files/16383021/LivePortrait.%2B.AnimateDiff.backgrounds.json)

**Comment by raochinmay6** [comment]
old version was good but when i update 1 hours ago then I start facing error

**Comment by raochinmay6** [comment]
or please give me old version

**Comment by kijai** [comment]
> old version was good but when i update 1 hours ago then I start facing error

Because that workflow is made with the old version, it needs an update.

**Comment by diffusionStable** [comment]
Hi everyone. If you've updated to the new version then the original workflow wont work and will give you the crop info error. 
The new updated workflow is here: https://github.com/kijai/ComfyUI-LivePortraitKJ/tree/main/examples

**Comment by tpcdaz** [comment]
> Hi everyone. If you've updated to the new version then the original workflow wont work and will give you the crop info error. The new updated workflow is here: https://github.com/kijai/ComfyUI-LivePortraitKJ/tree/main/examples

But the new workflow doesn't work. Just gives a cuda error even though everything is installed correctly. Cant we just have the old one that still works?

**Comment by kijai** [comment]
> > Hi everyone. If you've updated to the new version then the original workflow wont work and will give you the crop info error. The new updated workflow is here: https://github.com/kijai/ComfyUI-LivePortraitKJ/tree/main/examples
> 
> But the new workflow doesn't work. Just gives a cuda error even though everything is installed correctly. Cant we just have the old one that still works?

That's quite vague, If you get cuda errors, then everything is not installed correctly, rolling back the node version wouldn't change anything.

**Comment by tpcdaz** [comment]
> > > Hi everyone. If you've updated to the new version then the original workflow wont work and will give you the crop info error. The new updated workflow is here: https://github.com/kijai/ComfyUI-LivePortraitKJ/tree/main/examples
> > 
> > 
> > But the new workflow doesn't work. Just gives a cuda error even though everything is installed correctly. Cant we just have the old one that still works?
> 
> That's quite vague, If you get cuda errors, then everything is not installed correctly, rolling back the node version wouldn't change anything.

The issue only happens on your new workflow when insight face is selected. All other programs work fine,  even other comfy workflows that require insightface works fine. Your new workflow gives the error no matter what. Which is a shame.

**Comment by bozkut** [comment]
Any fixes, can not generate, help please?

**Comment by kijai** [comment]
It's been said so many times by now... use the example workflows or remake the nodes, this error is from using a workflow made with the old version.

**Comment by mkat2** [comment]
> It's been said so many times by now... use the example workflows or remake the nodes, this error is from using a workflow made with the old version.

But its not so easy as just replace one node for another since there are mutiple nodes for  input needed now because of the cropper input and also differnt outputs...is there an example  to change old node  to new inside workflows already usin g the old node?
